Página sobre Projeto GNU
ufla-gcc259/personalidades-sl pull request #11
Opened 2022-08-04 03:54 UTC by yanpisani

- **Descrição**: Foi alterado o arquivo _projeto-gnu.md_ com uma descrição sucinta sobre o que é o Projeto GNU, seus objetivos e relação com o **Software Livre**. Fora também adicionada o *logo* do GNU para embelezar a página, e também as respectivas fontes de nossas pesquisas.

- **Fluxo de trabalho**: O trabalho foi realizado por mim, **Yan Gustavo Andrade Pisani** (@yanpisani) e minha dupla, **Luis Henrique Saes Scandelai** (@luis-saes).  Após escolhermos uma *issue*, decidimos separar o que cada um iria pesquisar sobre o assunto. Eu decidi pesquisar sobre **o que é o projeto** e **como ele se relaciona com o Software Livre**, enquanto o Luis pesquisou sobre os **objetivos** e **status atual** do projeto. Feita as respectivas pesquisas, fiz o _fork_ do projeto, convidei o Luis como um colaborador, criamos uma _branch_ e adicionamos as informações e fontes, e fomos simultaneamente corrigindo o que cada um fez, a cada mudança que fazíamos no projeto, antes de realizar o PR (_Pull Request_). 

- **Dificuldades**: Não tivemos muita dificuldade para realizar o trabalho, pois há várias informações de fácil acesso sobre o Projeto GNU na internet. 

--------------------

Muito obrigado pela atenção, e aguardamos o feedback! 

![gnu](https://upload.wikimedia.org/wikipedia/commons/7/71/Heckert_gnu.small.png)

Fixes #4

2022-08-05 02:13 UTC, paulojunior-ufla requested changes

2022-08-05 02:13 UTC, paulojunior-ufla commented on stallman/projeto-gnu.md
> +- ## O que é o projeto?
Olá, @yanpisani .

Primeiramente, obrigado por sua contribuição. A propósito, gostei muito da descrição do fluxo de trabalho da equipe. Eu não sei se vocês ainda pretendem aprimorar esse PR, porém, já vou deixar meu _feedback_ aqui.

Por se tratar de uma página sobre a vida e as contribuições do Richard M. Stallman, eu gostaria que houvesse mais detalhes sobre a relação entre o projeto GNU e a pessoa do Stallman. Por exemplo, ele foi o autor principal do projeto, certo? Então, por que ele o criou? Qual era seu objetivo com ele? Qual a participação dele no projeto hoje em dia? Tipo essas coisas.

Obrigado mais uma vez.

2022-08-05 02:51 UTC, yanpisani commented on stallman/projeto-gnu.md
> +- ## O que é o projeto?
Muitíssimo obrigado pelo _feedback_, Paulo! Pretendemos aprimorar esse PR sim, especialmente com sua sugestão. Realmente seria interessante deixar claro a relação entre o Projeto GNU e seu criador, Stallman.

Sem o criador, não haveria projeto; não é mesmo?

Trabalharemos na correção o quanto antes.

2022-08-05 10:15 UTC, paulojunior-ufla commented on stallman/projeto-gnu.md
> +- ## O que é o projeto?
Ótimo, @yanpisani.

2022-08-06 03:15 UTC, luis-saes commented
Boa noite @paulojunior-ufla, tudo bem?

Algumas alterações foram feitas conforme recomendado, será que é possível realizar uma nova revisão e validar se mais alguma alteração precisa ser feita?

Muito obrigado!!

2022-08-06 23:59 UTC, paulojunior-ufla reviewed
Achei que ficou bem legal, @yanpisani e @luis-saes. Coloquei mais alguns pequenos comentários, mas, em termos de conteúdo, já está bom.

2022-08-06 23:59 UTC, paulojunior-ufla commented on stallman/projeto-gnu.md
> +- ## Quais são seus objetivos?
Remover o - antes dos ## para que subtítulo fique apenas assim:

## Quais são seus objetivos

2022-08-06 23:59 UTC, paulojunior-ufla commented on stallman/projeto-gnu.md
> +O projeto GNU é parte do *Movimento Software Livre*, uma campanha para a liberdade dos usuários de software. [^3]
Colocar as notas de rodapé dentro da frase, isto é, antes do ponto final. Por exemplo:

`O projeto GNU é parte do *Movimento Software Livre*, uma campanha para a liberdade dos usuários de software [^3].`

2022-08-06 23:59 UTC, paulojunior-ufla commented on stallman/projeto-gnu.md
> +No manifesto, Richard exprime a vontade de compartilhar os programas que gosta. Além disso, explica que abandonou seu trabalho no Laboratório de Inteligência Artificial do MIT, com objetivo de impedi
Eu acho que essa parte ficaria melhor logo no início do capítulo, pois fala, de início, que o Stallman foi o criador do projeto GNU.

2022-08-06 23:59 UTC, paulojunior-ufla approved these changes

2022-08-07 02:53 UTC, luis-saes commented
Boa noite @paulojunior-ufla, como andam as coisas?

Agradecemos imensamente pelo feedback, alterações foram realizadas e acredito que agora, estão de acordo com o discutido. Será que poderia realizar uma nova revisão e verificar se alguma outra mudança precisa ser realizada?

Muito obrigado!!

2022-08-08 17:18 UTC, paulojunior-ufla reviewed
Muito bom, @luis-saes. Coloquei mais alguns pequenos comentários para vocês.

Obrigado pelas contribuições.

Atenciosamente.
Paulo.

2022-08-08 17:18 UTC, paulojunior-ufla commented on stallman/projeto-gnu.md
> +Além disso, Richard Stallman fundou a *Free Software Foundation* em outubro de 1985, com objetivo de apoiar o movimento do Software Livre. Também, desde sua fundação até meados dos anos 90, os fundos
Que tal colocar um _link_ para a página sobre a FSF? Tem um grupo trabalhando sobre isso.

2022-08-08 17:18 UTC, paulojunior-ufla commented on stallman/projeto-gnu.md
> +- ## Qual o status do projeto atualmente?
Observem que tem alguns títulos que ainda estão com um `-` antes dos `##`. Por favor, deixem apenas os `##`.

2022-08-12 03:30 UTC, luis-saes commented
Boa noite, Paulo, tudo bem?

As alterações recomendadas foram realizadas, poderia validar, mais uma vez, por gentileza?

Muito obrigado!!

2022-08-12 13:05 UTC, paulojunior-ufla commented
Olá, @luis-saes e @yanpisani. Ficou ótimo. Estou bastante satisfeito com o resultado. Irei fazer o _merge_ em breve. Só peço que enviem novamente o _link_ deste PR na entrega final do trabalho, por favor.

2022-08-17 16:39 UTC, merged