Inclusão das informações sobre a Free Software Foundation
ufla-gcc259/personalidades-sl pull request #24
Opened 2022-08-08 01:39 UTC by wenderlemes

Descrição: foi realizada um pesquisa acerca da Free Software Foundation, filtrando e compilando tópicos relacionados a criação, propósito, relação com Software Livre, com Richard Stallman, projetos ativos etc. A principal base de informações foi a página oficial da própria fundação, que é bem rica em conteúdo histórico.

Fluxo de trabalho e equipe: a equipe foi formada por Mateus Tudeia e Wender Lemes. Considerando que foram sugeridas 4 questões norteadoras na Issue, fizemos a divisão de duas para cada integrante (Mateus com os dois primeiros tópicos, Wender com os dois últimos), sendo que cada um ficou responsável por revisar a adequação textual do outro colega. Sobre o fluxo de junção das alterações, Mateus realizou um PR para o fork de Wender, que por sua vez aceitou o merge das alterações e gerou o PR final.

Principais dificuldades: o site oficial da FSF está apenas parcialmente traduzido para o português, exigindo o domínio da segunda língua para o seu uso como fonte. Além disso, percebemos certa escassez de fontes fora o site oficial da FSF, talvez por a FSF já fazer bem o papel de concentrar as informações.

Fixes #5

2022-08-08 17:59 UTC, paulojunior-ufla requested changes
Olá, @wenderlemes.

Obrigado pela contribuição de vocês. O conteúdo sobre FSF está bem detalhado. Contudo, achei que faltou um pouco descrever a relação do Stallman com a FSF. Por se tratar de uma página sobre a vida e obra desta personalidade, seria interessante dar um foco maior nele e na sua relação com essa organização.

Atenciosamente.
Paulo.

2022-08-08 17:59 UTC, paulojunior-ufla commented on stallman/fsf.md
> +  Fundada pelo [Richard Stallman](https://pt.wikipedia.org/wiki/Richard_Matthew_Stallman), a FSF se dedica a eliminação de restrições sobre a cópia, redistribuição, estudo e modificação de programas
Colocar um espaço entre o final da palavra e a nota de rodapé, tipo `ferramentas [^4]`.

2022-08-08 17:59 UTC, paulojunior-ufla commented on stallman/fsf.md
> +  A Free Software Foundation (FSF), segundo a definição contida em seu próprio portal, é uma organização sem fins lucrativos com a missão mundial de promover a liberdade dos usuários de tecnologia. E
Colocar palavras estrangeiras em itálico, tipo _Free Software Foundation_

2022-08-09 02:28 UTC, wenderlemes commented
> Olá, @wenderlemes.
> 
> Obrigado pela contribuição de vocês. O conteúdo sobre FSF está bem detalhado. Contudo, achei que faltou um pouco descrever a relação do Stallman com a FSF. Por se tratar de uma página sobre a vida e obra desta personalidade, seria interessante dar um foco maior nele e na sua relação com essa organização.
> 
> Atenciosamente. Paulo.

Grato pelo feedback, @paulojunior-ufla, trabalharemos neles no decorrer da semana

2022-08-14 15:15 UTC, wenderlemes commented
> Olá, @wenderlemes.
> 
> Obrigado pela contribuição de vocês. O conteúdo sobre FSF está bem detalhado. Contudo, achei que faltou um pouco descrever a relação do Stallman com a FSF. Por se tratar de uma página sobre a vida e obra desta personalidade, seria interessante dar um foco maior nele e na sua relação com essa organização.
> 
> Atenciosamente. Paulo.

Boa tarde, @paulojunior-ufla, realizamos as alterações de formatação apontadas e criamos um tópico adicional para abordar a relação de Stallman com a FSF.

2022-08-15 00:52 UTC, paulojunior-ufla commented
Olá, @wenderlemes e demais membros da equipe. Muito obrigado pelas contribuições. Farei o _merge_ em breve. Por favor, envie o _link_ deste PR na tarefa de entrega final do trabalho prático.

2022-08-15 00:52 UTC, paulojunior-ufla approved these changes

2022-08-17 16:43 UTC, merged