Feat premios
ufla-gcc259/personalidades-sl pull request #25
Opened 2022-08-08 01:52 UTC by ThomazSIUFLA

Descrição: A equipe criou uma nova issue para trabalhar, relacionada aos prêmios, conquistas e reconhecimentos de Richard Stallman. Algumas pesquisas foram realizadas, e já foi criado o arquivo `premios-e-reconhecimentos.md` com o template para a execução da tarefa.

Fluxo de trabalho e equipe: A equipe é composta por João Vitor Soares Rezende, Pedro Henrique de Menezes e Thomaz Flanklin de Souza Jorge. Todos os membros da equipe contribuem com a pesquisa, Thomaz é o mantenedor do fork, iremos trabalhar com contribuições de todos os membros no mesmo projeto, porém cada integrante tem a responsabilidade de pesquisar sobre alguns tópicos sugeridos.

Principais dificuldades:

Fixes #13

2022-08-08 17:13 UTC, paulojunior-ufla requested changes

2022-08-08 17:13 UTC, paulojunior-ufla commented on stallman/premios-e-reconhecimentos.md
> +- 1990
Olá, @ThomazSIUFLA.

Ficou muito legal. Gostei mesmo! 
Tenho alguns pedidos para esta revisão:

1. Tentar padronizar a ordem em que as informações são colocadas. Por exemplo, sempre colocar o ano de entrega do prêmio o primeiro item da lista.
2. Colocar um rótulo, por exemplo: **Ano de entrega:**, para sabermos do que se trata o ano.
3. Para todos os prêmios, senti falta de uma referência de onde vocês encontraram essa informação.
4. Tem um prêmio, _Doutor honoris causa pela Universidade de Glasgow_, cuja formatação ficou diferente das demais.
   
Desde já, muito obrigado pela colaboração de vocês.

Atenciosamente.
Paulo.

2022-08-08 23:40 UTC, ThomazSIUFLA commented on stallman/premios-e-reconhecimentos.md
> +- 1990
Faremos as devidas correções!

2022-08-15 02:08 UTC, ThomazSIUFLA commented
Olá @paulojunior-ufla fizemos as alterações solicitadas e acrescentamos mais conteúdo.

2022-08-15 09:47 UTC, paulojunior-ufla approved these changes

2022-08-15 09:50 UTC, paulojunior-ufla commented
Ficou ótimo, @ThomazSIUFLA e demais membros da equipe. Obrigado por sua contribuição.

2022-08-17 16:56 UTC, merged