GIT
ufla-gcc259/personalidades-sl pull request #39
Opened 2023-01-24 22:41 UTC by StenioHenrique

Descrição: Para a construção do trabalho realizamos pesquisas que contassem história sobre o Git e só após começamos a construção do texto.

Fluxo de trabalho da equipe: Nosso grupo é formado por Ademar, Gustavo, Stênio e Vitória, nos organizamos em duplas (Ademar e Gustavo / Stênio e Vitória). A primeira ficou com as perguntas pares e a segunda com as ímpares, mas ficou aberta a discussão para caso houvesse dúvida ou algo do tipo. 
Utilizamos um documento compartilhado com todos para que fossem expostos os materiais entrados e um rascunho do texto que estava sendo produzido. Após todas as formatações, um integrante fez a commit do conteúdo. 

Principais dificuldades: Para a construção do conteúdo foram realizadas pesquisas com um certo filtro, visto que foram encontrados muitos materiais repetidos e que às vezes não era bem aquilo que esperávamos.

Fixes: #31

2023-01-25 00:03 UTC, paulojunior-ufla requested changes

2023-01-25 00:03 UTC, paulojunior-ufla commented on linus/git.md
> +## O que é o projeto[^1]?
Colocar um espaço em branco entre a palavra e sua nota de rodapé, assim: "...projeto [^1]"

2023-01-25 00:03 UTC, paulojunior-ufla commented on linus/git.md
> +O Git é um Sistema de Controle de Versões Distribuído (DVCS), esse sistema registra todas as alterações realizadas em um determinado código, dessa forma é possível visualizar todo o histórico detalha
DVCS - Colocar a descrição da sigla em inglês também.

2023-01-25 00:03 UTC, paulojunior-ufla commented on linus/git.md
> +![Exemplo de GitFlow utilizando o GIT](https://user-images.githubusercontent.com/56547429/214272903-6f55b7d7-2a8f-4ab4-a35d-b9b24ee66cf7.png)
A figura ficou sem explicação. Assim, sugiro que seja removida, pois o texto parece consistente sem ela.

2023-01-25 00:03 UTC, paulojunior-ufla commented on linus/git.md
> +O projeto surgiu durante o nascimento do kernel do linux, onde todas as alterações e correções eram compartilhadas em arquivos, chegaram a usar um outro software chamado DVCS para controle de versão,
linux: escrever com letra maiúscula aqui e nos demais locais onde a palavra aparece.

2023-01-25 00:03 UTC, paulojunior-ufla commented on linus/git.md
> +## Qual o status do projeto atualmente[^4]?
Senti que faltou falar um pouco mais da relação do Linus com o Git. Uma forma de melhorar isso seria explicar qual o tipo de contribuição do Linus atualmente com o projeto "Git".

2023-01-25 00:04 UTC, paulojunior-ufla commented
Olá, @StenioHenrique. Agradeço imensamente a contribuição de vocês. Coloquei algumas solicitações de mudança ao longo do texto. Qualquer dúvida, estou à disposição.

2023-01-26 22:39 UTC, StenioHenrique commented on linus/git.md
> +## Qual o status do projeto atualmente[^4]?
Professor, não conseguimos achar se o Linus contribui ou não no projeto Git atualmente. Adicionamos algumas informações da época que foi criada, o senhor acha que atende?

2023-02-01 17:16 UTC, merged