Linus Torvalds Vida pessoal
ufla-gcc259/personalidades-sl pull request #42
Opened 2023-01-25 02:49 UTC by HarturFranco

Descrição: Foi realizado uma pesquisa em posts de blogs, wikis e literatura sobre a vida pessoal do Linus Torvalds para a realização do trabalho.

Fluxo de trabalho e equipe: A equipe é composta por Arthur Franco, Thiago Salles, João Paulo Paiva e Luiz Soares. Foram divididos os tópicos  sugeridos pelo mantenedor do projeto entre a equipe, cada membro fez sua pesquisa sobre seu respectivo tópico. Arthur ficou responsável pelo Pull-Request e informações sobre data de nascimento e sobre a família de Linus, Luiz foi responsável por produzir sobre sua infância/adolescência, Thiago pela personalidade e João Paulo pelos assuntos de interesse e outras informações relevantes sobre a vida pessoal.

Principais dificuldades: A equipe encontrou dificuldades para encontrar informações mais relevantes sobre a mãe de Linus além de seu trabalho como jornalista.

Fixes #27

2023-01-25 10:24 UTC, paulojunior-ufla requested changes

2023-01-25 10:24 UTC, paulojunior-ufla commented on linus/vida-pessoal.md
> +Linus Torvalds nasceu em Helsinque, capital da Finlândia, no dia 28 de dezembro de 1969.[^1]
Colocar um espaço entre o final da palavra e a nota de rodapé.

2023-01-25 10:24 UTC, paulojunior-ufla commented on linus/vida-pessoal.md
> +## Personalidade de Linus Torvalds
As frases desta seção/parágrafo estão muito longas. Favor dividir cada frase em outras duas ou três.

2023-01-25 10:24 UTC, paulojunior-ufla commented on linus/vida-pessoal.md
> +Linus é bastante conhecido pela sua personalidade orgulhosa, crítica e arrogante, isto devido a seus conflitos e discussões um pouco acaloradas, com alguns membros da comunidade de Software Livre ou
Vocês comentam sobre uma entrevista que o Linus deu. Seria bom ter uma referência para essa entrevista. Depois da palavra "mundo" tem um ponto final: verificar!

2023-01-25 10:24 UTC, paulojunior-ufla commented on linus/vida-pessoal.md
> +Torvalds gota de ouvir música e seu gênero favorito é rock clássico (anos 60 e Beatles)[^9].
"gota": verificar grafia

2023-01-25 10:25 UTC, paulojunior-ufla commented
Olá, @HarturFranco. Muito obrigado pelas contribuições. Coloquei algumas solicitações de mudança para vocês ao longo do texto. Qualquer dúvida, estou à disposição.

2023-01-31 16:44 UTC, HarturFranco commented on linus/vida-pessoal.md
> +Linus Torvalds nasceu em Helsinque, capital da Finlândia, no dia 28 de dezembro de 1969.[^1]
Corrigimos o pedido e outras inconsistências nas notas de rodapé no seguinte commit:

#[04127dd](https://github.com/ufla-gcc259/personalidades-sl/pull/42/commits/04127dd5bb96a7aad0f466bb1d5b4bf9344c64dd)

2023-01-31 19:26 UTC, ThiagoSallesSantos commented on linus/vida-pessoal.md
> +Linus é bastante conhecido pela sua personalidade orgulhosa, crítica e arrogante, isto devido a seus conflitos e discussões um pouco acaloradas, com alguns membros da comunidade de Software Livre ou
- Correções solicitadas referente a falta de referência a entrevista e também a pontuação após o termo mundo, foram corrigidas. - Commit referente a essas correções foi: #fd39fc1757ff6048fe9b366ecb631ee8837dd13f
- Correções solicitadas referente ao espaçamento entre o texto e a referência, foram corrigidas. - Commit referente a essa correção foi: #09a5513bc26332662a9997a3cbfe27b69cebb095

2023-01-31 23:04 UTC, joaopaulo7 commented on linus/vida-pessoal.md
> +Torvalds gota de ouvir música e seu gênero favorito é rock clássico (anos 60 e Beatles)[^9].
Corrigimos o pedido no seguinte commit:

#49d2c48

2023-01-31 23:57 UTC, ThiagoSallesSantos commented on linus/vida-pessoal.md
> +## Personalidade de Linus Torvalds
Correções solicitadas referente ao tamanho das frases, foram corrigidas. - Commit referente a essa correção foi: #4894fc793b25f6f8ffe1a9823ec67f4a3a3b0656

2023-02-01 17:19 UTC, merged