Update producoes.md
ufla-gcc259/personalidades-sl pull request #59
Opened 2023-10-25 20:51 UTC by juliacteixeira

Commits iniciais contanto sobre a história da ASF

2023-10-31 17:27 UTC, paulojunior-ufla requested changes
Olá, @juliacteixeira. Obrigado pela contribuição de vocês, ficou ótimo. 

Fiz alguns pequenos pedidos de correção ao longo do texto. Além disso, a descrição do PR não está no formato correto, segundo o guia de contribuições do projeto.

No mais, fico aguardando a versão final, com as correções, para que eu faça o merge.

2023-10-31 17:27 UTC, paulojunior-ufla commented on apache/producoes.md
> +1. **"Hadoop: The Definitive Guide"** - [Link para o livro](https://www.oreilly.com/library/view/hadoop-the-definitive/9781491901687/)
Acrescentar informação sobre os autores, ano de publicação, editora e número de páginas.

2023-10-31 17:27 UTC, paulojunior-ufla commented on apache/producoes.md
> +1. **Apache Documentação Oficial** - [Link para a documentação oficial](https://www.apache.org/docs/)
Acho que o link poderia ser o próprio nome do tópico, assim: [Documentação oficial Apache](http://www.apache.org)

2023-10-31 17:27 UTC, paulojunior-ufla commented on apache/producoes.md
> +## 1. [Apache HTTP Server](https://projects.apache.org/project.html?httpd-http_server)
Para os projetos que estão sendo estudados por outras equipes neste trabalho, colocar o link para a página desses projetos neste repositório.

2023-11-07 01:14 UTC, juliacteixeira commented
Descrição: Inserção de livros, informando autor, data de publicação, editora e quantidade de paginas, links de artigos e documentos, além de links para os projetos e uma explicação básica dos principais.

Equipe: Fabrício de Oliveira Carvalho
Pedro Henrique Marques Siqueira
Vidaflor Ferreira Costa 
Julia Carvalho de Teixeira

Fixes #58

2023-11-07 01:14 UTC, juliacteixeira commented
Descrição: Inserção de livros, informando autor, data de publicação, editora e quantidade de paginas, links de artigos e documentos, além de links para os projetos e uma explicação básica dos principais.

Equipe: Fabrício de Oliveira Carvalho
Pedro Henrique Marques Siqueira
Vidaflor Ferreira Costa
Julia Carvalho de Teixeira

Fixes #58

2023-11-07 01:15 UTC, juliacteixeira commented
Descrição: Inserção de livros, informando autor, data de publicação, editora e quantidade de paginas, links de artigos e documentos, além de links para os projetos e uma explicação básica dos principais.

Equipe: Fabrício de Oliveira Carvalho
Pedro Henrique Marques Siqueira
Vidaflor Ferreira Costa
Julia Carvalho de Teixeira

Fixes #58

2023-11-13 17:04 UTC, paulojunior-ufla approved these changes

2023-11-13 17:04 UTC, merged