Historia
ufla-gcc259/personalidades-sl pull request #60
Opened 2023-10-29 16:58 UTC by mJR-exe

Descrição: Foram complementados os tópicos da issue #49 explicando a história do Apache Software Foundation, com as devidas referências.

Equipe: Maurício Júnior, Fabrício Smargiasse, Gustavo Marzoque e Pedro Garcia.

Fixes: #49

2023-10-31 17:21 UTC, paulojunior-ufla requested changes
Olá, @mJR-exe. Obrigado pela contribuição de vocês, ficou ótimo. 

Fiz alguns pequenos pedidos de correção ao longo do texto. 

No mais, fico aguardando a versão final, com as correções, para que eu faça o merge.

2023-10-31 17:21 UTC, paulojunior-ufla commented on apache/historia.md
> +A Apache Software Foundation (ASF) conhecida também apenas como Apache Foundation ou Fundação Apache é uma organização sem fins lucrativos criada para suportar os projetos de código aberto, principal
Colocar palavras estrangeiras usadas ao longo do texto em _itálico_.

2023-10-31 17:21 UTC, paulojunior-ufla commented on apache/historia.md
> +Um dos objetivos da ASF é proteger legalmente os participantes dos seus projetos, e prevenir que o nome Apache seja utilizado por outras organizações sem a devida permissão.[^1]
Dar um espaço entre a último caractere da frase e a referência.

2023-10-31 17:21 UTC, paulojunior-ufla commented on apache/historia.md
> +## Por que esse nome Apache?
No PR da equipe que está trabalhando com curiosidades, eles falam que o nome não foi dado por causa da tribo. Para que não haja contradições, peço que entrem em contato com a outra equipe e vejam se conseguem verificar a informação.

2023-11-05 13:35 UTC, mJR-exe commented
Correções feitas.

2023-11-05 13:36 UTC, mJR-exe commented
> Olá, @mJR-exe. Obrigado pela contribuição de vocês, ficou ótimo.
> 
> Fiz alguns pequenos pedidos de correção ao longo do texto.
> 
> No mais, fico aguardando a versão final, com as correções, para que eu faça o merge.


Correções feitas.

2023-11-13 17:02 UTC, paulojunior-ufla approved these changes

2023-11-13 17:03 UTC, merged