Apache License
ufla-gcc259/personalidades-sl pull request #63
Opened 2023-10-30 18:28 UTC by taianers

Descrição: apresentação dos detalhes do projeto Apache License, incluindo descrição do projeto, objetivos, importância, status atual e algumas informações interessantes.

Equipe: Eduardo Carvalho Leite, Igor Freire de Morais, Iorrana Maria do Nascimento, Luiz Carlos Bessa de Lima e Taiane Rodrigues de Sousa

Fixes #55

2023-10-31 17:10 UTC, paulojunior-ufla requested changes
Olá, @taianers. Obrigado pela contribuição de vocês, ficou ótimo. 

Algumas poucas recomendações:

* Colocar palavras estrangeiras, como open-source e disclaimer, em _itálico_.
* Dar um espaço entre a referência e a última palavra do texto, assim: "última palavra [1]".

No mais, fico aguardando a versão final, com as correções, para que eu faça o merge.

2023-10-31 19:26 UTC, lcbessa commented
Correções feitas!

2023-10-31 21:49 UTC, paulojunior-ufla approved these changes

2023-10-31 21:50 UTC, paulojunior-ufla commented
Obrigado, @lcbessa. Farei o _merge_ em breve!

2023-11-13 17:00 UTC, paulojunior-ufla approved these changes

2023-11-13 17:00 UTC, merged