Issue #52
ufla-gcc259/personalidades-sl pull request #64
Opened 2023-10-30 22:20 UTC by HCuri1

Descrição: Adicionou-se informações referentes ao projeto "Apache Kafka", sendo: o que é, objetivos, importância para a fundação Apache e para o Software Livre, status atual do projeto e página oficial.

Equipe: Breno Campos Barbosa
Henrique Curi de Miranda
José Vítor Andrade Marques
Nathan Araújo Silva
Paulo Eduardo Soares Rezende

Fixes #52

2023-10-31 16:59 UTC, paulojunior-ufla requested changes
Olá, @HCuri1. Obrigado pela contribuição de vocês, ficou ótimo. 

Fiz alguns pequenos pedidos de correção ao longo do texto. 

No mais, fico aguardando a versão final, com as correções, para que eu faça o merge.

2023-10-31 16:59 UTC, paulojunior-ufla commented on apache/kafka.md
> +O Apache Kafka é uma plataforma open-source de streaming de dados desenvolvido pela Apache Software Foundation, escrita em Scala e Java. A plataforma foi um sistema interno criado pelo LinkedIn e pos
Colocar palavras estrangeiras, como streaming e open-source em itálico.

2023-10-31 16:59 UTC, paulojunior-ufla commented on apache/kafka.md
> +Sendo projetado para lidar com armazenamento, processamento e ingestão de fluxo de dados em tempo real, o Kafka é utilizado em casos que análise em tempo real é necessário, como em sistema de monitor
necessário -> necessária

2023-10-31 16:59 UTC, paulojunior-ufla commented on apache/kafka.md
> +O projeto tem por objetivo o desenvolvimento, em Scala e Java, de uma plataforma para tratamento de dados em tempo real. Tem também por objetivo ser uma plataforma unificada, de alta capacidade e de
Dar um espaço entre a referência e o ponto final.

2023-10-31 23:19 UTC, HCuri1 reviewed
Correções feitas

2023-11-01 16:51 UTC, paulojunior-ufla approved these changes

2023-11-01 16:52 UTC, paulojunior-ufla commented
@HCuri1, obrigado pela contribuição. Farei o _merge_ em breve.

2023-11-13 16:58 UTC, paulojunior-ufla approved these changes

2023-11-13 16:59 UTC, merged