Apache Openoffice
ufla-gcc259/personalidades-sl pull request #66
Opened 2023-10-30 23:26 UTC by rock051

Segue para análise as alterações sugeridas pelo grupo: "documentation good first issue #54 "

2023-10-31 02:39 UTC, rock051 commented
Segue para análise as alterações sugeridas pelo grupo: "documentation good first issue https://github.com/ufla-gcc259/personalidades-sl/issues/54 "

2023-10-31 11:01 UTC, paulojunior-ufla requested changes
Olá, @rock051. Obrigado pelas contribuições.

Entendo que o PR precisa de alguns ajustes para que possa ser aprovado, a saber:

1. O texto não cita fontes (referências) de onde foi baseado. Verificar o guia de contribuições do projeto, para saber mais como adicionar referências ao projeto.

2. Eu achei a descrição dos aplicativos muito longa. Sugiro resumir cada aplicativo com um parágrafo que descreva seu objetivo e principais funcionalidades.

3. Várias perguntas interessantes para o contexto da disciplina (que estavam na descrição da issue) não foram respondidas, a saber:
* o que é o projeto?
* qual é ou quais são seus objetivos?
* qual a importância desse projeto para a fundação Apache e para o Software Livre como um todo?
* qual o status do projeto atualmente?
* qual a página oficial do projeto?

4. Por fim, a descrição do PR não está no formato correto, segundo o guia de contribuições do projeto.
No mais, fico aguardando a versão final, com as correções, para que eu faça o merge.

2023-10-31 11:01 UTC, paulojunior-ufla commented on apache/openoffice.md
> + writer
writer -> Writer

2023-10-31 11:01 UTC, paulojunior-ufla commented on apache/openoffice.md
> +Para todos os seus documentos
Frase meio solta no texto. Verificar!

2023-10-31 11:01 UTC, paulojunior-ufla commented on apache/openoffice.md
> +Os Assistentes retiram toda a pressão de criar documentos padrão como cartas, faxes, agendas, minutas ou mesmo levar a cabo tarefas mais complexas como por exemplo listas de correio electrónico. É cl
electrónico -> eletrônico

2023-11-05 20:51 UTC, ValterGN commented
Descrição: levantamento das principais informações sobre o projeto Apache OpenOffice, examinando suas características,  aplicativos e funcionalidades, proporcionando uma compreensão sobre o projeto como um todo.

Equipe: Claudio Manoel dos Reis Junior, Fernando Mauricio Roque, Valter Granato Neto

Fixes #54

2023-11-13 17:05 UTC, paulojunior-ufla approved these changes

2023-11-13 17:06 UTC, merged