Detalhes sobre o projeto Apache HTTP Server
ufla-gcc259/personalidades-sl pull request #68
Opened 2023-10-31 01:44 UTC by LeoJunioYuri

Descrição: Desenvolvimento de uma página com detalhes sobre o projeto Apache HTTP Server para a disciplina Desenvolvimento de Software Livre, do Departamento de Ciência da Computação da Universidade Federal de Lavras ([DCC/UFLA](http://www.dcc.ufla.br/)).

Equipe: João Vitor Veronezi, Leonardo Basso, Mateus Peternelli, Rafael Moura.

Fixes #51

2023-10-31 10:43 UTC, paulojunior-ufla requested changes
Olá, @LeoJunioYuri. Obrigado pela contribuição de vocês, ficou ótimo. 

Fiz alguns pequenos pedidos de correção ao longo do texto. 

No mais, fico aguardando a versão final, com as correções, para que eu faça o merge.

2023-10-31 10:43 UTC, paulojunior-ufla commented on apache/kafka.md
> -# Apache Kafka
Eu não sei o que foi mudado no arquivo do Kafka, mas gostaria de pedir que vocês removessem esse arquivo do commit, para que não entre em conflito com o trabalho do outro grupo.

2023-10-31 10:43 UTC, paulojunior-ufla commented on apache/server.md
> +O Apache HTTP Server é um servidor web poderoso e flexível que pode ser usado para hospedar uma ampla gama de sites e aplicativos. Ele é usado por uma ampla gama de organizações, incluindo empresas,
Melhorar o parágrafo para evitar a repetição da expressão "ampla gama".

2023-10-31 10:43 UTC, paulojunior-ufla commented on apache/server.md
> +## Benefícios
Eu juntaria as seções "características", "benefícios" e "objetivos" em uma só. Estão um pouco repetitivas.

2023-10-31 10:43 UTC, paulojunior-ufla commented on apache/server.md
> +## Benefícios específicos
O conteúdo da seção Benefícios específicos poderia ser distribuído nas seções anteriores.

2023-10-31 15:36 UTC, LeoJunioYuri commented
Alterações feitas, professor! Obrigado por pontuá-las.
Sigo no aguardo da aprovação da PR.
Qualquer coisa estou a disposição.
Atenciosamente,
Leonardo

2023-11-13 16:51 UTC, paulojunior-ufla approved these changes

2023-11-13 16:51 UTC, merged