Curiosidades e polêmicas #56
ufla-gcc259/personalidades-sl pull request #69
Opened 2023-10-31 04:33 UTC by jamillydanielle

Descrição: Desenvolvimento da sessão de Curiosidades e Polêmicas do Apache para a disciplina de Desenvolvimento de Software Livre, do Departamento de Ciência da Computação da Universidade Federal de Lavras

<LINHA EM BRANCO>

Equipe: Victor Huggo, João Victor e Jamilly Danielle

<LINHA EM BRANCO>

Fixes #56

2023-10-31 04:35 UTC, jamillydanielle commented
#69

2023-10-31 04:35 UTC, jamillydanielle commented
Fixes #69

2023-10-31 10:12 UTC, paulojunior-ufla requested changes
Olá, @jamillydanielle. Obrigado pela contribuição de vocês, ficou ótimo. 

Fiz alguns pequenos pedidos de correção ao longo do texto. Além disso, na descrição do PR, fazer a seguinte alteração, por favor: sessão -> seção

No mais, fico aguardando a versão final, com as correções, para que eu faça o merge.

2023-10-31 10:12 UTC, paulojunior-ufla commented on apache/curiosidades-e-polemicas.md
> +- O projeto Apache foi fundado em 1995 por Robert Tappan Morris, Jr., um dos criadores da internet.
Robert Tappan Morris, Jr -> colocar um link para a página dele na Wiki

2023-10-31 10:12 UTC, paulojunior-ufla commented on apache/curiosidades-e-polemicas.md
> +- O Apache é um software de código aberto, o que significa que seu código-fonte está disponível para qualquer pessoa examinar, modificar e distribuir de acordo com os termos da Licença Pública Apache
Esse ponto é mais uma característica do que uma curiosidade. Sugiro removê-lo.

2023-10-31 10:12 UTC, paulojunior-ufla commented on apache/curiosidades-e-polemicas.md
> +- O Apache é altamente extensível por meio do uso de módulos. Você pode adicionar funcionalidades extras ao servidor web instalando módulos específicos, que podem lidar com coisas como autenticação,
Esse ponto é mais uma característica do que uma curiosidade. Sugiro removê-lo.

2023-10-31 10:12 UTC, paulojunior-ufla commented on apache/curiosidades-e-polemicas.md
> +- O Apache também é associado ao projeto Apache Tomcat, que é um servidor de aplicação web Java amplamente usado para executar aplicativos baseados em Java, como aplicativos da web e serviços da web.
Esse ponto é mais uma característica do que uma curiosidade. Sugiro removê-lo.

2023-10-31 10:12 UTC, paulojunior-ufla commented on apache/curiosidades-e-polemicas.md
> +- O Apache é conhecido por ser executado em uma ampla variedade de sistemas operacionais, incluindo várias versões do Unix, Linux, Windows e mais.
Esse ponto é mais uma característica do que uma curiosidade. Sugiro removê-lo.

2023-10-31 10:12 UTC, paulojunior-ufla commented on apache/curiosidades-e-polemicas.md
> +1. Em 2008, o Apache foi acusado de espionagem por um grupo de hackers. Os hackers alegaram que o Apache estava coletando dados de usuários de seus produtos.
Faltou uma referência para essa informação.

2023-10-31 10:12 UTC, paulojunior-ufla commented on apache/curiosidades-e-polemicas.md
> +2. Em 2013, o Apache foi criticado por sua falta de diversidade, com apenas 10% de seus desenvolvedores sendo mulheres. No decorrer do tempo, a orgaização tomou medidas para aumentar a diversidade em
Corrigir a palavra organização

2023-10-31 10:12 UTC, paulojunior-ufla commented on apache/curiosidades-e-polemicas.md
> +### Aspectos históricos
Eu acho que essa seção pode ser removida, para não ficar redundante com o trabalho de outro grupo. Apenas o tópico sobre o modelo de desenvolvimento colaborativo poderia ir para a seção "Curiosidades".

2023-11-03 22:17 UTC, jamillydanielle commented on apache/curiosidades-e-polemicas.md
> +1. Em 2008, o Apache foi acusado de espionagem por um grupo de hackers. Os hackers alegaram que o Apache estava coletando dados de usuários de seus produtos.
Não encontrei onde achei a informação, então removi.

2023-11-03 22:45 UTC, jamillydanielle commented
Comentários resolvidos.

2023-11-13 16:49 UTC, paulojunior-ufla approved these changes

2023-11-13 16:50 UTC, merged